// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testapp2Api.Models;

namespace Testapp2Api.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Testapp2Api.Models.Complain", b =>
                {
                    b.Property<string>("ComplainerName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("complain");

                    b.Property<int>("houseNo");

                    b.HasKey("ComplainerName");

                    b.ToTable("complain");
                });
#pragma warning restore 612, 618
        }
    }
}
